export default [
    {
        id_product: 19,
        id_supplier: 2,
        id_manufacturer: 1,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "13.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_14",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 1,
        uploadable_files: 0,
        text_fields: 1,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "standard",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>Customize your mug with the text of your choice. A mood, a message, a quote... It's up to you! Maximum number of characters: ---</p>",
        description_short: "<p>White Ceramic Mug. 325ml</p>",
        link_rewrite: "customizable-mug",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Customizable mug",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 18,
        id_supplier: 2,
        id_manufacturer: 2,
        id_category_default: 7,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "12.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_10",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 36,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The Mountain fox notebook is the best option to write down your most ingenious ideas. At work, at home or when traveling, its endearing design and manufacturing quality will make you feel like writing! 90 gsm paper / double spiral binding.</p>",
        description_short:
            "<p>120 sheets notebook with hard cover made of recycled cardboard. 16x22cm</p>",
        link_rewrite: "hummingbird-notebook",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Hummingbird notebook",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 17,
        id_supplier: 2,
        id_manufacturer: 2,
        id_category_default: 7,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "12.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_9",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 32,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The Mountain fox notebook is the best option to write down your most ingenious ideas. At work, at home or when traveling, its endearing design and manufacturing quality will make you feel like writing! 90 gsm paper / double spiral binding.</p>",
        description_short:
            "<p>120 sheets notebook with hard cover made of recycled cardboard. 16x22cm</p>",
        link_rewrite: "brown-bear-notebook",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Brown bear notebook",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 16,
        id_supplier: 2,
        id_manufacturer: 2,
        id_category_default: 7,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "12.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_8",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 28,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The Mountain fox notebook is the best option to write down your most ingenious ideas. At work, at home or when traveling, its endearing design and manufacturing quality will make you feel like writing! 90 gsm paper / double spiral binding.</p>",
        description_short:
            "<p>120 sheets notebook with hard cover made of recycled cardboard. 16x22cm</p>",
        link_rewrite: "mountain-fox-notebook",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Mountain fox notebook",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 15,
        id_supplier: 2,
        id_manufacturer: 0,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "35.000000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_21",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 1,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "pack",
        id_shop: 1,
        id_lang: 1,
        description: "",
        description_short:
            "<p>Mug The Adventure Begins + Framed poster Today is a good day 40x60cm </p>",
        link_rewrite: "pack-mug-framed-poster",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Pack Mug + Framed poster",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: null,
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 14,
        id_supplier: 2,
        id_manufacturer: 2,
        id_category_default: 9,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "9.000000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_20",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 1,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "virtual",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>You have a custom printing creative project? The vector graphic Mountain fox illustration can be used for printing purpose on any support, without size limitation. </p>",
        description_short:
            "<p>Vector graphic, format: svg. Download for personal, private and non-commercial use.</p>",
        link_rewrite: "hummingbird-vector-graphics",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Hummingbird - Vector graphics",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 13,
        id_supplier: 2,
        id_manufacturer: 2,
        id_category_default: 9,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "9.000000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_19",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 1,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "virtual",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>You have a custom printing creative project? The vector graphic Mountain fox illustration can be used for printing purpose on any support, without size limitation. </p>",
        description_short:
            "<p>Vector graphic, format: svg. Download for personal, private and non-commercial use.</p>",
        link_rewrite: "brown-bear-vector-graphics",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Brown bear - Vector graphics",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 12,
        id_supplier: 2,
        id_manufacturer: 2,
        id_category_default: 9,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "9.000000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_18",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 1,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "virtual",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>You have a custom printing creative project? The vector graphic Mountain fox illustration can be used for printing purpose on any support, without size limitation. </p>",
        description_short:
            "<p>Vector graphic, format: svg. Download for personal, private and non-commercial use.</p>",
        link_rewrite: "mountain-fox-vector-graphics",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Mountain fox - Vector graphics",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 11,
        id_supplier: 2,
        id_manufacturer: 1,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "18.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_17",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 26,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The hummingbird cushion will add a graphic and colorful touch to your sofa, armchair or bed. Create a modern and zen atmosphere that inspires relaxation. Cover 100% cotton, machine washable at 60° / Filling 100% hypoallergenic polyester.</p>",
        description_short:
            "<p>Cushion with removable cover and invisible zip on the back. 32x32cm</p>",
        link_rewrite: "hummingbird-cushion",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Hummingbird cushion",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 10,
        id_supplier: 2,
        id_manufacturer: 1,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "18.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_16",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 24,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The brown bear cushion will add a graphic and colorful touch to your sofa, armchair or bed. Create a modern and zen atmosphere that inspires relaxation. Cover 100% cotton, machine washable at 60° / Filling 100% hypoallergenic polyester.</p>",
        description_short:
            "<p>Cushion with removable cover and invisible zip on the back. 32x32cm</p>",
        link_rewrite: "brown-bear-cushion",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Brown bear cushion",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 9,
        id_supplier: 2,
        id_manufacturer: 1,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "18.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_15",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 22,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The mountain fox cushion will add a graphic and colorful touch to your sofa, armchair or bed. Create a modern and zen atmosphere that inspires relaxation. Cover 100% cotton, machine washable at 60° / Filling 100% hypoallergenic polyester.</p>",
        description_short:
            "<p>Cushion with removable cover and invisible zip on the back. 32x32cm</p>",
        link_rewrite: "mountain-fox-cushion",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Mountain fox cushion",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 8,
        id_supplier: 2,
        id_manufacturer: 1,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "11.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_13",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "404",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "standard",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>Add an optimistic touch to your morning coffee and start the day in a good mood! 8,2cm diameter / 9,5cm height / 0.43kg. Dishwasher-proof.</p>",
        description_short: "<p>White Ceramic Mug. 325ml</p>",
        link_rewrite: "mug-today-is-a-good-day",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Mug Today is a good day",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 7,
        id_supplier: 2,
        id_manufacturer: 1,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "11.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_12",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "standard",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The adventure begins with a cup of coffee. Set out to conquer the day! 8,2cm diameter / 9,5cm height / 0.43kg. Dishwasher-proof.</p>",
        description_short: "<p>White Ceramic Mug. 325ml</p>",
        link_rewrite: "mug-the-adventure-begins",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Mug The adventure begins",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 6,
        id_supplier: 2,
        id_manufacturer: 1,
        id_category_default: 8,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "11.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_11",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 0,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "standard",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The best is yet to come! Start the day off right with a positive thought. 8,2cm diameter / 9,5cm height / 0.43kg. Dishwasher-proof.</p>",
        description_short: "<p>White Ceramic Mug, 325ml.</p>",
        link_rewrite: "mug-the-best-is-yet-to-come",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Mug The best is yet to come",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Accessories supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 5,
        id_supplier: 1,
        id_manufacturer: 2,
        id_category_default: 9,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "29.000000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_7",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 19,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The best is yet to come! Give your walls a voice with a framed poster. This aesthethic, optimistic poster will look great in your desk or in an open-space office. Painted wooden frame with passe-partout for more depth.</p>",
        description_short:
            "<p>Printed on rigid paper with matt finish and smooth surface.</p>",
        link_rewrite: "today-is-a-good-day-framed-poster",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Today is a good day Framed poster",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Fashion supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 4,
        id_supplier: 1,
        id_manufacturer: 2,
        id_category_default: 9,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "29.000000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_5",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "404",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 16,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The best is yet to come! Give your walls a voice with a framed poster. This aesthethic, optimistic poster will look great in your desk or in an open-space office. Painted wooden frame with passe-partout for more depth.</p>",
        description_short:
            "<p>Printed on rigid matt finish and smooth surface.</p>",
        link_rewrite: "the-adventure-begins-framed-poster",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "The adventure begins Framed poster",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Fashion supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 3,
        id_supplier: 1,
        id_manufacturer: 2,
        id_category_default: 9,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "29.000000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_6",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "301-category",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 13,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>The best is yet to come! Give your walls a voice with a framed poster. This aesthethic, optimistic poster will look great in your desk or in an open-space office. Painted wooden frame with passe-partout for more depth.</p>",
        description_short:
            "<p>Printed on rigid matt paper and smooth surface.</p>",
        link_rewrite: "the-best-is-yet-to-come-framed-poster",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "The best is yet to come' Framed poster",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Graphic Corner",
        supplier_name: "Fashion supplier",
        rate: 0,
        tax_name: "",
    },
    {
        id_product: 2,
        id_supplier: 1,
        id_manufacturer: 1,
        id_category_default: 5,
        id_shop_default: 1,
        id_tax_rules_group: 9,
        on_sale: 0,
        online_only: 0,
        ean13: "",
        isbn: "",
        upc: "",
        mpn: "",
        ecotax: "0.000000",
        quantity: 0,
        minimal_quantity: 1,
        low_stock_threshold: null,
        low_stock_alert: 0,
        price: "35.900000",
        wholesale_price: "5.490000",
        unity: "",
        unit_price: "0.000000",
        unit_price_ratio: "0.000000",
        additional_shipping_cost: "0.000000",
        reference: "demo_3",
        supplier_reference: "",
        location: "",
        width: "0.000000",
        height: "0.000000",
        depth: "0.000000",
        weight: "0.300000",
        out_of_stock: 2,
        additional_delivery_times: 1,
        quantity_discount: 0,
        customizable: 0,
        uploadable_files: 0,
        text_fields: 0,
        active: 1,
        redirect_type: "404",
        id_type_redirected: 0,
        available_for_order: 1,
        available_date: "0000-00-00",
        show_condition: 0,
        condition: "new",
        show_price: 1,
        indexed: 1,
        visibility: "both",
        cache_is_pack: 0,
        cache_has_attachments: 0,
        is_virtual: 0,
        cache_default_attribute: 9,
        date_add: "2023-06-09 02:29:43",
        date_upd: "2023-06-09 06:42:44",
        advanced_stock_management: 0,
        pack_stock_type: 3,
        state: 1,
        product_type: "combinations",
        id_shop: 1,
        id_lang: 1,
        description:
            "<p>Studio Design' PolyFaune collection features classic products with colorful patterns, inspired by the traditional japanese origamis. To wear with a chino or jeans. The sublimation textile printing process provides an exceptional color rendering and a color, guaranteed overtime.</p>",
        description_short:
            "<p>Regular fit, round neckline, long sleeves. 100% cotton, brushed inner side for extra comfort. </p>",
        link_rewrite: "brown-bear-printed-sweater",
        meta_description: "",
        meta_keywords: "",
        meta_title: "",
        name: "Hummingbird printed sweater",
        available_now: "",
        available_later: "",
        delivery_in_stock: "",
        delivery_out_stock: "",
        manufacturer_name: "Studio Design",
        supplier_name: "Fashion supplier",
        rate: 0,
        tax_name: "",
    },
];
